spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ld
    username: lottodream
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.board.newb_board_server
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    board:
      newb_board_server: trace


client.url: http://localhost:3000/
