spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/ld
    username: lottodream
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  type-aliases-package: com.board.newb_board_server
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    board:
      newb_board_server: trace

application:
  security:
    jwt:
      secret-key: VlwEyVBsYt9V7zq57TejMnVUyewkrqwekkeWERkdfksazblYcfPQye08f7MGEWRweVA9XkHa
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days